### ISSUE TITLE
Ready for an official release?

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/image_field_caption#2]
Hello @sternhagel! This module seems like it could be handy for a site I'm currently building; thank you for working on this port!

Are there any current blockers to issuing an official release of this module that appears on https://backdropcms.org/modules, or any problems with running this on a production site as far as you know?

**Comment by sternhagel** [comment]
Hello @jackaponte 
Sorry for my late response, for some reason I didn't get a notification about your message.

I'm using the module on a production site myself, and I'm not having any issues with it, so there are no blockers AFAIK - you're just the first person asking for a release, that's why there isn't one yet. As this is the first Backdrop module I'm maintaining I'm not really sure about how to issue an official release, but I'll try to find out and get this working.

**Comment by sternhagel** [comment]
I just released an initial beta version of this module.

I'm marking it as beta and non-production because AFAIK I'm the only one who tested it yet. So I'd like to do some more testing before releasing a stable version.

@jackaponte If you're still interested in using this module, I'd really appreciate if you could so some testing on your website and give me feedback about any issues you might encounter.

**Comment by jackaponte** [comment]
Hi @sternhagel, thank you for this response! I am indeed still using the module and would be happy to provide feedback.

I'd like to install the newest version of the module in order to do that testing, but I don't see any initial beta releases on https://github.com/backdrop-contrib/image_field_caption -- in the right-hand column Releases says "No releases published," not even a beta release.

Let me know if there's a different place I should be looking to for the beta release you worked on a few weeks ago.

**Comment by olafgrabienski** [comment]
> in the right-hand column Releases says "No releases published," not even a beta release

Maybe because it's a beta? @jackaponte If you click on the "Releases" heading (https://github.com/backdrop-contrib/image_field_caption/releases), you'll find the releases page where the beta is listed.

**Comment by jackaponte** [comment]
> Maybe because it's a beta? @jackaponte If you click on the "Releases" heading (https://github.com/backdrop-contrib/image_field_caption/releases), you'll find the releases page where the beta is listed.

Ah, just needed one more click! Thanks @olafgrabienski. I've confirmed I've got the up-to-date version of the module and will report anything I find, @sternhagel!

**Comment by sternhagel** [comment]
@olafgrabienski Thanks for answering - you're too fast for me ;-)
@jackaponte Thanks for testing - looking forward to releasing a stable version...

**Comment by robertgarrigos** [comment]
I'm interested in a release of this module also and will test it. :-) Shouldn't we leave this issue open until a test report is done??

**Comment by sternhagel** [comment]
Sorry for not posting here for such a long time. I'm not using this module in any project anymore, so I kind of lost track of it.
From my point of view there were no serious issues anymore, and we could try to release a stable version.

@jackaponte @robertgarrigos did you find anything testing this module? If your testing was successful, would be great if you'd report here.

**Comment by robertgarrigos** [comment]
I'm using it without any problem.

**Comment by keiserjb** [comment]
I'm using this on multiple sites and had to come track it down for another.  I think a release so it shows up in the installer would be good.

**Comment by olafgrabienski** [comment]
> From my point of view there were no serious issues anymore, and we could try to release a stable version.

Sounds good!

**Comment by sternhagel** [comment]
Thanks everybody for your feedback! As nobody reported any blocking issues so far, I decided to tag the current state as a stable release. 
The module appears on the official module list now: https://backdropcms.org/modules
